// Code generated by goctl. DO NOT EDIT.
package types

// The basic response with data | 基础带数据信息
// swagger:model BaseDataInfo
type BaseDataInfo struct {
	// Error code | 错误代码
	Code int `json:"code"`
	// Message | 提示信息
	Msg string `json:"msg"`
	// Data | 数据
	Data string `json:"data,omitempty"`
}

// The basic response with data | 基础带数据信息
// swagger:model BaseListInfo
type BaseListInfo struct {
	// The total number of data | 数据总数
	Total uint64 `json:"total"`
	// Data | 数据
	Data string `json:"data,omitempty"`
}

// The basic response without data | 基础不带数据信息
// swagger:model BaseMsgResp
type BaseMsgResp struct {
	// Error code | 错误代码
	Code int `json:"code"`
	// Message | 提示信息
	Msg string `json:"msg"`
}

// The page request parameters | 列表请求参数
// swagger:model PageInfo
type PageInfo struct {
	// Page number | 第几页
	// required : true
	// min : 0
	Page uint64 `json:"page" validate:"required,number,gt=0"`
	// Page size | 单页数据行数
	// required : true
	// max : 100000
	PageSize uint64 `json:"pageSize" validate:"required,number,lt=100000"`
}

// Basic ID request | 基础ID参数请求
// swagger:model IDReq
type IDReq struct {
	// ID
	// Required: true
	Id uint64 `json:"id" validate:"number"`
}

// Basic IDs request | 基础ID数组参数请求
// swagger:model IDsReq
type IDsReq struct {
	// IDs
	// Required: true
	Ids []uint64 `json:"ids"`
}

// Basic ID request | 基础ID地址参数请求
// swagger:model IDPathReq
type IDPathReq struct {
	// ID
	// Required: true
	Id uint64 `path:"id"`
}

// Basic path UUID request | 基础UUID地址参数请求
// swagger:model UUIDPathReq
type UUIDPathReq struct {
	// ID
	// Required: true
	Id string `path:"id"`
}

// Basic UUID request | 基础UUID参数请求
// swagger:model UUIDReq
type UUIDReq struct {
	// ID
	// Required: true
	// Max length: 36
	Id string `json:"id" validate:"len=36"`
}

// Basic UUID array request | 基础UUID数组参数请求
// swagger:model UUIDsReq
type UUIDsReq struct {
	// Ids
	// Required: true
	Ids []string `json:"ids"`
}

// The base ID response data | 基础ID信息
// swagger:model BaseIDInfo
type BaseIDInfo struct {
	// ID
	Id *uint64 `json:"id,optional"`
	// Create date | 创建日期
	CreatedAt *int64 `json:"createdAt,optional"`
	// Update date | 更新日期
	UpdatedAt *int64 `json:"updatedAt,optional"`
}

// The base UUID response data | 基础UUID信息
// swagger:model BaseUUIDInfo
type BaseUUIDInfo struct {
	// ID
	Id *string `json:"id,optional"`
	// Create date | 创建日期
	CreatedAt *int64 `json:"createdAt,optional"`
	// Update date | 更新日期
	UpdatedAt *int64 `json:"updatedAt,optional"`
}

// The request params of setting boolean status | 设置状态参数
// swagger:model StatusCodeReq
type StatusCodeReq struct {
	// ID
	Id string `json:"id"`
	// Status code | 状态码
	Status uint64 `json:"status" validate:"number"`
}

// The data when upload finished | 上传完成数据
// swagger:model UploadInfo
type UploadInfo struct {
	// File name | 文件名称
	Name string `json:"name"`
	// File path | 文件路径
	Url string `json:"url"`
}

// The response data when upload finished | 上传完成返回的数据
// swagger:model UploadResp
type UploadResp struct {
	BaseDataInfo
	// The  data when upload finished | 上传完成数据
	Data UploadInfo `json:"data"`
}

// Update file information params | 更新文件信息参数
// swagger:model UpdateFileReq
type UpdateFileReq struct {
	// ID
	// Required : true
	ID string `json:"id"`
	// File name | 文件名
	// Required : true
	Name *string `json:"name,optional" validate:"max=50"`
	// File tag | 文件标签
	FileTagIds []uint64 `json:"tagIds,optional"`
}

// Get file list params | 获取文件列表参数
// swagger:model FileListReq
type FileListReq struct {
	PageInfo
	// File type | 文件类型
	// max length : 10
	FileType *uint8 `json:"fileType,optional" validate:"omitempty,max=10"`
	// File name | 文件名
	// max length : 50
	FileName *string `json:"fileName,optional" validate:"omitempty,max=50"`
	// Create date period | 创建日期时间段
	Period []string `json:"period,optional"`
	// FileTags' Id | 标签 ID
	FileTagIds []uint64 `json:"tagIds,optional"`
	// Status | 状态
	Status *uint8 `json:"status,optional"`
}

// The response data of file information | 文件信息数据
// swagger:model FileInfo
type FileInfo struct {
	BaseUUIDInfo
	// User's UUID | 用户的UUID
	UserUUID *string `json:"userUUID"`
	// File name | 文件名
	Name *string `json:"name"`
	// File type | 文件类型
	FileType *uint8 `json:"fileType"`
	// File size | 文件大小
	Size *uint64 `json:"size"`
	// File path | 文件路径
	Path *string `json:"path"`
	// File public status | 文件公开状态
	// false private true public | false 私人, true公开
	Status *uint8 `json:"status"`
	// The public URL | 公开访问的链接
	PublicPath *string `json:"publicPath"`
	// FileTags' Id | 标签 ID
	FileTagIds []uint64 `json:"tagIds"`
}

// The response data of file information list | 文件信息列表数据
// swagger:model FileListResp
type FileListResp struct {
	BaseDataInfo
	// The file list data | 文件信息列表数据
	Data FileListInfo `json:"data"`
}

// swagger:model FileListInfo
type FileListInfo struct {
	BaseListInfo
	// The file list data | 文件信息列表数据
	Data []FileInfo `json:"data"`
}

// The response data of file tag information | 文件标签信息
// swagger:model FileTagInfo
type FileTagInfo struct {
	BaseIDInfo
	// Status
	Status *uint8 `json:"status,optional"`
	// Name
	Name *string `json:"name,optional"`
	// Remark
	Remark *string `json:"remark,optional"`
}

// The response data of file tag list | 文件标签列表数据
// swagger:model FileTagListResp
type FileTagListResp struct {
	BaseDataInfo
	// FileTag list data | 文件标签列表数据
	Data FileTagListInfo `json:"data"`
}

// FileTag list data | 文件标签列表数据
// swagger:model FileTagListInfo
type FileTagListInfo struct {
	BaseListInfo
	// The API list data | 文件标签列表数据
	Data []FileTagInfo `json:"data"`
}

// Get file tag list request params | 文件标签列表请求参数
// swagger:model FileTagListReq
type FileTagListReq struct {
	PageInfo
	// Name
	Name *string `json:"name,optional"`
	// Remark
	Remark *string `json:"remark,optional"`
}

// FileTag information response | 文件标签信息返回体
// swagger:model FileTagInfoResp
type FileTagInfoResp struct {
	BaseDataInfo
	// FileTag information | 文件标签数据
	Data FileTagInfo `json:"data"`
}

// The response data of cloud file information | 云文件信息
// swagger:model CloudFileInfo
type CloudFileInfo struct {
	BaseUUIDInfo
	// State | 状态
	State *bool `json:"state,optional"`
	// Name | 名称
	Name *string `json:"name,optional"`
	// Url | 网络地址
	Url *string `json:"url,optional"`
	// Size | 文件大小
	Size *uint64 `json:"size,optional"`
	// File type | 文件类型
	FileType *uint8 `json:"fileType,optional"`
	// User ID | 上传用户的 ID
	UserId *string `json:"userId,optional"`
	// Provider ID | 提供商的 ID
	ProviderId *uint64 `json:"providerId,optional"`
	// Tag ID | 标签 ID
	TagIds []uint64 `json:"tagIds,optional"`
}

// The response data of cloud file list | 云文件列表数据
// swagger:model CloudFileListResp
type CloudFileListResp struct {
	BaseDataInfo
	// CloudFile list data | 云文件列表数据
	Data CloudFileListInfo `json:"data"`
}

// CloudFile list data | 云文件列表数据
// swagger:model CloudFileListInfo
type CloudFileListInfo struct {
	BaseListInfo
	// The API list data | 云文件列表数据
	Data []CloudFileInfo `json:"data"`
}

// Get cloud file list request params | 云文件列表请求参数
// swagger:model CloudFileListReq
type CloudFileListReq struct {
	PageInfo
	// Name | 文件名
	Name *string `json:"name,optional"`
	// Provider ID | 提供商 ID
	ProviderId *uint64 `json:"providerId,optional"`
	// Tag ID | 标签 ID
	TagIds []uint64 `json:"tagIds,optional"`
}

// CloudFile information response | 云文件信息返回体
// swagger:model CloudFileInfoResp
type CloudFileInfoResp struct {
	BaseDataInfo
	// CloudFile information | 云文件数据
	Data CloudFileInfo `json:"data"`
}

// The response data of storage provider information | 服务提供商信息
// swagger:model StorageProviderInfo
type StorageProviderInfo struct {
	BaseIDInfo
	// State | 状态
	State *bool `json:"state,optional"`
	// Name | 云服务提供商名称
	Name *string `json:"name,optional"`
	// Bucket | 存储桶
	Bucket *string `json:"bucket,optional"`
	// Provider Name | 云服务提供商名称
	ProviderName *string `json:"providerName,optional"`
	// Secret Id
	SecretId *string `json:"secretId,optional"`
	// Secret Key
	SecretKey *string `json:"secretKey,optional"`
	// Region | 地区
	Region *string `json:"region,optional"`
	// Whether is Default | 是否为默认
	IsDefault *bool `json:"isDefault,optional"`
}

// The response data of storage provider list | 服务提供商列表数据
// swagger:model StorageProviderListResp
type StorageProviderListResp struct {
	BaseDataInfo
	// StorageProvider list data | 服务提供商列表数据
	Data StorageProviderListInfo `json:"data"`
}

// StorageProvider list data | 服务提供商列表数据
// swagger:model StorageProviderListInfo
type StorageProviderListInfo struct {
	BaseListInfo
	// The API list data | 服务提供商列表数据
	Data []StorageProviderInfo `json:"data"`
}

// Get storage provider list request params | 服务提供商列表请求参数
// swagger:model StorageProviderListReq
type StorageProviderListReq struct {
	PageInfo
	// Name | 名称
	Name *string `json:"name,optional"`
	// Bucket | 存储桶
	Bucket *string `json:"bucket,optional"`
	// Provider Name | 提供商名称
	ProviderName *string `json:"providerName,optional"`
}

// StorageProvider information response | 服务提供商信息返回体
// swagger:model StorageProviderInfoResp
type StorageProviderInfoResp struct {
	BaseDataInfo
	// StorageProvider information | 服务提供商数据
	Data StorageProviderInfo `json:"data"`
}

// The response data of cloud file tag information | 云文件标签信息
// swagger:model CloudFileTagInfo
type CloudFileTagInfo struct {
	BaseIDInfo
	// Status
	Status *uint8 `json:"status,optional"`
	// Name
	Name *string `json:"name,optional"`
	// Remark
	Remark *string `json:"remark,optional"`
}

// The response data of cloud file tag list | 云文件标签列表数据
// swagger:model CloudFileTagListResp
type CloudFileTagListResp struct {
	BaseDataInfo
	// CloudFileTag list data | 云文件标签列表数据
	Data CloudFileTagListInfo `json:"data"`
}

// CloudFileTag list data | 云文件标签列表数据
// swagger:model CloudFileTagListInfo
type CloudFileTagListInfo struct {
	BaseListInfo
	// The API list data | 云文件标签列表数据
	Data []CloudFileTagInfo `json:"data"`
}

// Get cloud file tag list request params | 云文件标签列表请求参数
// swagger:model CloudFileTagListReq
type CloudFileTagListReq struct {
	PageInfo
	// Name
	Name *string `json:"name,optional"`
	// Remark
	Remark *string `json:"remark,optional"`
}

// Cloud file tag information response | 云文件标签信息返回体
// swagger:model CloudFileTagInfoResp
type CloudFileTagInfoResp struct {
	BaseDataInfo
	// Cloud file tag information | 云文件标签数据
	Data CloudFileTagInfo `json:"data"`
}
