// Code generated by goctl. DO NOT EDIT.
package types

// The basic response with data | 基础带数据信息
// swagger:model BaseDataInfo
type BaseDataInfo struct {
	// Error code | 错误代码
	Code int `json:"code"`
	// Message | 提示信息
	Msg string `json:"msg"`
	// Data | 数据
	Data string `json:"data,omitempty"`
}

// The basic response with data | 基础带数据信息
// swagger:model BaseListInfo
type BaseListInfo struct {
	// The total number of data | 数据总数
	Total uint64 `json:"total"`
	// Data | 数据
	Data string `json:"data,omitempty"`
}

// The basic response without data | 基础不带数据信息
// swagger:model BaseMsgResp
type BaseMsgResp struct {
	// Error code | 错误代码
	Code int `json:"code"`
	// Message | 提示信息
	Msg string `json:"msg"`
}

// The simplest message | 最简单的信息
type SimpleMsg struct {
	// Message | 信息
	Msg string `json:"msg"`
}

// The page request parameters | 列表请求参数
// swagger:model PageInfo
type PageInfo struct {
	// Page number | 第几页
	Page uint64 `json:"page" validate:"number"`
	// Page size | 单页数据行数
	// max length : 100000
	PageSize uint64 `json:"pageSize" validate:"number,max=100000"`
}

// Basic ID request | 基础id参数请求
// swagger:model IDReq
type IDReq struct {
	// ID
	// Required: true
	Id uint64 `json:"id" validate:"number"`
}

// Basic ID request in path | 基础ID地址参数请求
// swagger:model IDPathReq
type IDPathReq struct {
	// ID
	// Required: true
	Id uint64 `path:"id"`
}

// Basic UUID request | 基础UUID参数请求
// swagger:model UUIDReq
type UUIDReq struct {
	// UUID
	// max length : 36
	// min length : 36
	UUID string `json:"UUID" validate:"len=36"`
}

// The base response data | 基础信息
// swagger:model BaseInfo
type BaseInfo struct {
	// ID
	Id uint64 `json:"id"`
	// Create date | 创建日期
	CreatedAt int64 `json:"createdAt,optional"`
	// Update date | 更新日期
	UpdatedAt int64 `json:"updatedAt,optional"`
}

// The request params of setting boolean status | 设置状态参数
// swagger:model StatusCodeReq
type StatusCodeReq struct {
	// ID
	Id uint64 `json:"id" validate:"number"`
	// Status code | 状态码
	Status uint64 `json:"status" validate:"number"`
}

// The data when upload finished | 上传完成数据
// swagger:model UploadInfo
type UploadInfo struct {
	// File name | 文件名称
	Name string `json:"name"`
	// File path | 文件路径
	Url string `json:"url"`
}

// The response data when upload finished | 上传完成返回的数据
// swagger:model UploadResp
type UploadResp struct {
	BaseDataInfo
	// The  data when upload finished | 上传完成数据
	Data UploadInfo `json:"data"`
}

// Update file information params | 更新文件信息参数
// swagger:model UpdateFileReq
type UpdateFileReq struct {
	// ID
	// Required : true
	ID uint64 `json:"id"`
	// File name | 文件名
	// Required : true
	// Max length: 50
	Name string `json:"name" validate:"max=50"`
}

// Get file list params | 获取文件列表参数
// swagger:model FileListReq
type FileListReq struct {
	PageInfo
	// File type | 文件类型
	// max length : 10
	FileType uint8 `json:"fileType,optional" validate:"omitempty,alpha,max=10"`
	// File name | 文件名
	// max length : 50
	FileName string `json:"fileName,optional" validate:"max=50"`
	// Create date period | 创建日期时间段
	Period []string `json:"period,optional"`
}

// The response data of file information | 文件信息数据
// swagger:model FileInfo
type FileInfo struct {
	BaseInfo
	// UUID
	UUID string `json:"UUID"`
	// User's UUID | 用户的UUID
	UserUUID string `json:"userUUID"`
	// File name | 文件名
	Name string `json:"name"`
	// File type | 文件类型
	FileType uint8 `json:"fileType"`
	// File size | 文件大小
	Size uint64 `json:"size"`
	// File path | 文件路径
	Path string `json:"path"`
	// File public status | 文件公开状态
	// false private true public | false 私人, true公开
	Status uint8 `json:"status"`
	// The public URL | 公开访问的链接
	PublicPath string `json:"publicPath"`
}

// The response data of file information list | 文件信息列表数据
// swagger:model FileListResp
type FileListResp struct {
	BaseDataInfo
	// The file list data | 文件信息列表数据
	Data FileListInfo `json:"data"`
}

// swagger:model FileListInfo
type FileListInfo struct {
	BaseListInfo
	// The file list data | 文件信息列表数据
	Data []FileInfo `json:"data"`
}
