// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FmsFilesColumns holds the columns for the "fms_files" table.
	FmsFilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "uuid", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "file_type", Type: field.TypeUint8},
		{Name: "size", Type: field.TypeUint64},
		{Name: "path", Type: field.TypeString},
		{Name: "user_uuid", Type: field.TypeString},
		{Name: "md5", Type: field.TypeString},
	}
	// FmsFilesTable holds the schema information for the "fms_files" table.
	FmsFilesTable = &schema.Table{
		Name:       "fms_files",
		Columns:    FmsFilesColumns,
		PrimaryKey: []*schema.Column{FmsFilesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FmsFilesTable,
	}
)

func init() {
	FmsFilesTable.Annotation = &entsql.Annotation{
		Table: "fms_files",
	}
}
