// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FmsCloudFilesColumns holds the columns for the "fms_cloud_files" table.
	FmsCloudFilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "state", Type: field.TypeBool, Nullable: true, Comment: "State true: normal false: ban | 状态 true 正常 false 禁用", Default: true},
		{Name: "name", Type: field.TypeString, Comment: "The file's name | 文件名"},
		{Name: "url", Type: field.TypeString, Comment: "The file's url | 文件地址"},
		{Name: "size", Type: field.TypeUint64, Comment: "The file's size | 文件大小"},
		{Name: "file_type", Type: field.TypeUint8, Comment: "The file's type | 文件类型"},
		{Name: "user_id", Type: field.TypeString, Comment: "The user who upload the file | 上传用户的 ID"},
		{Name: "storage_provider_id", Type: field.TypeUint64, Comment: "The storage provider who store the file | 文件存储提供商 ID"},
	}
	// FmsCloudFilesTable holds the schema information for the "fms_cloud_files" table.
	FmsCloudFilesTable = &schema.Table{
		Name:       "fms_cloud_files",
		Columns:    FmsCloudFilesColumns,
		PrimaryKey: []*schema.Column{FmsCloudFilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "fms_cloud_files_fms_storage_providers_cloudfiles",
				Columns:    []*schema.Column{FmsCloudFilesColumns[9]},
				RefColumns: []*schema.Column{FmsStorageProvidersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "cloudfile_name",
				Unique:  false,
				Columns: []*schema.Column{FmsCloudFilesColumns[4]},
			},
			{
				Name:    "cloudfile_file_type",
				Unique:  false,
				Columns: []*schema.Column{FmsCloudFilesColumns[7]},
			},
		},
	}
	// FmsCloudFileTagsColumns holds the columns for the "fms_cloud_file_tags" table.
	FmsCloudFileTagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Comment: "Status 1: normal 2: ban | 状态 1 正常 2 禁用", Default: 1},
		{Name: "name", Type: field.TypeString, Comment: "CloudFileTag's name | 标签名称"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "The remark of tag | 标签的备注"},
	}
	// FmsCloudFileTagsTable holds the schema information for the "fms_cloud_file_tags" table.
	FmsCloudFileTagsTable = &schema.Table{
		Name:       "fms_cloud_file_tags",
		Columns:    FmsCloudFileTagsColumns,
		PrimaryKey: []*schema.Column{FmsCloudFileTagsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "cloudfiletag_name",
				Unique:  false,
				Columns: []*schema.Column{FmsCloudFileTagsColumns[4]},
			},
		},
	}
	// FmsFilesColumns holds the columns for the "fms_files" table.
	FmsFilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Comment: "Status 1: normal 2: ban | 状态 1 正常 2 禁用", Default: 1},
		{Name: "name", Type: field.TypeString, Comment: "File's name | 文件名称"},
		{Name: "file_type", Type: field.TypeUint8, Comment: "File's type | 文件类型"},
		{Name: "size", Type: field.TypeUint64, Comment: "File's size | 文件大小"},
		{Name: "path", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString, Comment: "User's UUID | 用户的 UUID"},
		{Name: "md5", Type: field.TypeString, Comment: "The md5 of the file | 文件的 md5"},
	}
	// FmsFilesTable holds the schema information for the "fms_files" table.
	FmsFilesTable = &schema.Table{
		Name:       "fms_files",
		Columns:    FmsFilesColumns,
		PrimaryKey: []*schema.Column{FmsFilesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "file_user_id",
				Unique:  false,
				Columns: []*schema.Column{FmsFilesColumns[8]},
			},
			{
				Name:    "file_file_type",
				Unique:  false,
				Columns: []*schema.Column{FmsFilesColumns[5]},
			},
		},
	}
	// FmsFileTagsColumns holds the columns for the "fms_file_tags" table.
	FmsFileTagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Comment: "Status 1: normal 2: ban | 状态 1 正常 2 禁用", Default: 1},
		{Name: "name", Type: field.TypeString, Comment: "FileTag's name | 标签名称"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "The remark of tag | 标签的备注"},
	}
	// FmsFileTagsTable holds the schema information for the "fms_file_tags" table.
	FmsFileTagsTable = &schema.Table{
		Name:       "fms_file_tags",
		Columns:    FmsFileTagsColumns,
		PrimaryKey: []*schema.Column{FmsFileTagsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "filetag_name",
				Unique:  false,
				Columns: []*schema.Column{FmsFileTagsColumns[4]},
			},
		},
	}
	// FmsStorageProvidersColumns holds the columns for the "fms_storage_providers" table.
	FmsStorageProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "state", Type: field.TypeBool, Nullable: true, Comment: "State true: normal false: ban | 状态 true 正常 false 禁用", Default: true},
		{Name: "name", Type: field.TypeString, Unique: true, Comment: "The cloud storage service name | 服务名称"},
		{Name: "bucket", Type: field.TypeString, Comment: "The cloud storage bucket name | 云存储服务的存储桶"},
		{Name: "secret_id", Type: field.TypeString, Comment: "The secret ID | 密钥 ID"},
		{Name: "secret_key", Type: field.TypeString, Comment: "The secret key | 密钥 Key"},
		{Name: "endpoint", Type: field.TypeString, Comment: "The service URL | 服务器地址"},
		{Name: "folder", Type: field.TypeString, Nullable: true, Comment: "The folder in cloud | 云服务目标文件夹"},
		{Name: "region", Type: field.TypeString, Comment: "The service region | 服务器所在地区"},
		{Name: "is_default", Type: field.TypeBool, Comment: "Is it the default provider | 是否为默认提供商", Default: false},
		{Name: "use_cdn", Type: field.TypeBool, Comment: "Does it use CDN | 是否使用 CDN", Default: false},
		{Name: "cdn_url", Type: field.TypeString, Nullable: true, Comment: "CDN URL | CDN 地址"},
	}
	// FmsStorageProvidersTable holds the schema information for the "fms_storage_providers" table.
	FmsStorageProvidersTable = &schema.Table{
		Name:       "fms_storage_providers",
		Columns:    FmsStorageProvidersColumns,
		PrimaryKey: []*schema.Column{FmsStorageProvidersColumns[0]},
	}
	// CloudFileTagCloudFilesColumns holds the columns for the "cloud_file_tag_cloud_files" table.
	CloudFileTagCloudFilesColumns = []*schema.Column{
		{Name: "cloud_file_tag_id", Type: field.TypeUint64},
		{Name: "cloud_file_id", Type: field.TypeUUID},
	}
	// CloudFileTagCloudFilesTable holds the schema information for the "cloud_file_tag_cloud_files" table.
	CloudFileTagCloudFilesTable = &schema.Table{
		Name:       "cloud_file_tag_cloud_files",
		Columns:    CloudFileTagCloudFilesColumns,
		PrimaryKey: []*schema.Column{CloudFileTagCloudFilesColumns[0], CloudFileTagCloudFilesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "cloud_file_tag_cloud_files_cloud_file_tag_id",
				Columns:    []*schema.Column{CloudFileTagCloudFilesColumns[0]},
				RefColumns: []*schema.Column{FmsCloudFileTagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "cloud_file_tag_cloud_files_cloud_file_id",
				Columns:    []*schema.Column{CloudFileTagCloudFilesColumns[1]},
				RefColumns: []*schema.Column{FmsCloudFilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// FileTagFilesColumns holds the columns for the "file_tag_files" table.
	FileTagFilesColumns = []*schema.Column{
		{Name: "file_tag_id", Type: field.TypeUint64},
		{Name: "file_id", Type: field.TypeUUID},
	}
	// FileTagFilesTable holds the schema information for the "file_tag_files" table.
	FileTagFilesTable = &schema.Table{
		Name:       "file_tag_files",
		Columns:    FileTagFilesColumns,
		PrimaryKey: []*schema.Column{FileTagFilesColumns[0], FileTagFilesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "file_tag_files_file_tag_id",
				Columns:    []*schema.Column{FileTagFilesColumns[0]},
				RefColumns: []*schema.Column{FmsFileTagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "file_tag_files_file_id",
				Columns:    []*schema.Column{FileTagFilesColumns[1]},
				RefColumns: []*schema.Column{FmsFilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FmsCloudFilesTable,
		FmsCloudFileTagsTable,
		FmsFilesTable,
		FmsFileTagsTable,
		FmsStorageProvidersTable,
		CloudFileTagCloudFilesTable,
		FileTagFilesTable,
	}
)

func init() {
	FmsCloudFilesTable.ForeignKeys[0].RefTable = FmsStorageProvidersTable
	FmsCloudFilesTable.Annotation = &entsql.Annotation{
		Table: "fms_cloud_files",
	}
	FmsCloudFileTagsTable.Annotation = &entsql.Annotation{
		Table: "fms_cloud_file_tags",
	}
	FmsFilesTable.Annotation = &entsql.Annotation{
		Table: "fms_files",
	}
	FmsFileTagsTable.Annotation = &entsql.Annotation{
		Table: "fms_file_tags",
	}
	FmsStorageProvidersTable.Annotation = &entsql.Annotation{
		Table: "fms_storage_providers",
	}
	CloudFileTagCloudFilesTable.ForeignKeys[0].RefTable = FmsCloudFileTagsTable
	CloudFileTagCloudFilesTable.ForeignKeys[1].RefTable = FmsCloudFilesTable
	FileTagFilesTable.ForeignKeys[0].RefTable = FmsFileTagsTable
	FileTagFilesTable.ForeignKeys[1].RefTable = FmsFilesTable
}
