// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/suyuan32/simple-admin-file/ent/cloudfile"
	"github.com/suyuan32/simple-admin-file/ent/cloudfiletag"
)

// CloudFileTagCreate is the builder for creating a CloudFileTag entity.
type CloudFileTagCreate struct {
	config
	mutation *CloudFileTagMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (cftc *CloudFileTagCreate) SetCreatedAt(t time.Time) *CloudFileTagCreate {
	cftc.mutation.SetCreatedAt(t)
	return cftc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cftc *CloudFileTagCreate) SetNillableCreatedAt(t *time.Time) *CloudFileTagCreate {
	if t != nil {
		cftc.SetCreatedAt(*t)
	}
	return cftc
}

// SetUpdatedAt sets the "updated_at" field.
func (cftc *CloudFileTagCreate) SetUpdatedAt(t time.Time) *CloudFileTagCreate {
	cftc.mutation.SetUpdatedAt(t)
	return cftc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cftc *CloudFileTagCreate) SetNillableUpdatedAt(t *time.Time) *CloudFileTagCreate {
	if t != nil {
		cftc.SetUpdatedAt(*t)
	}
	return cftc
}

// SetStatus sets the "status" field.
func (cftc *CloudFileTagCreate) SetStatus(u uint8) *CloudFileTagCreate {
	cftc.mutation.SetStatus(u)
	return cftc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cftc *CloudFileTagCreate) SetNillableStatus(u *uint8) *CloudFileTagCreate {
	if u != nil {
		cftc.SetStatus(*u)
	}
	return cftc
}

// SetName sets the "name" field.
func (cftc *CloudFileTagCreate) SetName(s string) *CloudFileTagCreate {
	cftc.mutation.SetName(s)
	return cftc
}

// SetRemark sets the "remark" field.
func (cftc *CloudFileTagCreate) SetRemark(s string) *CloudFileTagCreate {
	cftc.mutation.SetRemark(s)
	return cftc
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (cftc *CloudFileTagCreate) SetNillableRemark(s *string) *CloudFileTagCreate {
	if s != nil {
		cftc.SetRemark(*s)
	}
	return cftc
}

// SetID sets the "id" field.
func (cftc *CloudFileTagCreate) SetID(u uint64) *CloudFileTagCreate {
	cftc.mutation.SetID(u)
	return cftc
}

// AddCloudFileIDs adds the "cloud_files" edge to the CloudFile entity by IDs.
func (cftc *CloudFileTagCreate) AddCloudFileIDs(ids ...uuid.UUID) *CloudFileTagCreate {
	cftc.mutation.AddCloudFileIDs(ids...)
	return cftc
}

// AddCloudFiles adds the "cloud_files" edges to the CloudFile entity.
func (cftc *CloudFileTagCreate) AddCloudFiles(c ...*CloudFile) *CloudFileTagCreate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cftc.AddCloudFileIDs(ids...)
}

// Mutation returns the CloudFileTagMutation object of the builder.
func (cftc *CloudFileTagCreate) Mutation() *CloudFileTagMutation {
	return cftc.mutation
}

// Save creates the CloudFileTag in the database.
func (cftc *CloudFileTagCreate) Save(ctx context.Context) (*CloudFileTag, error) {
	cftc.defaults()
	return withHooks(ctx, cftc.sqlSave, cftc.mutation, cftc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cftc *CloudFileTagCreate) SaveX(ctx context.Context) *CloudFileTag {
	v, err := cftc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cftc *CloudFileTagCreate) Exec(ctx context.Context) error {
	_, err := cftc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cftc *CloudFileTagCreate) ExecX(ctx context.Context) {
	if err := cftc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cftc *CloudFileTagCreate) defaults() {
	if _, ok := cftc.mutation.CreatedAt(); !ok {
		v := cloudfiletag.DefaultCreatedAt()
		cftc.mutation.SetCreatedAt(v)
	}
	if _, ok := cftc.mutation.UpdatedAt(); !ok {
		v := cloudfiletag.DefaultUpdatedAt()
		cftc.mutation.SetUpdatedAt(v)
	}
	if _, ok := cftc.mutation.Status(); !ok {
		v := cloudfiletag.DefaultStatus
		cftc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cftc *CloudFileTagCreate) check() error {
	if _, ok := cftc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CloudFileTag.created_at"`)}
	}
	if _, ok := cftc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CloudFileTag.updated_at"`)}
	}
	if _, ok := cftc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CloudFileTag.name"`)}
	}
	return nil
}

func (cftc *CloudFileTagCreate) sqlSave(ctx context.Context) (*CloudFileTag, error) {
	if err := cftc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cftc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cftc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	cftc.mutation.id = &_node.ID
	cftc.mutation.done = true
	return _node, nil
}

func (cftc *CloudFileTagCreate) createSpec() (*CloudFileTag, *sqlgraph.CreateSpec) {
	var (
		_node = &CloudFileTag{config: cftc.config}
		_spec = sqlgraph.NewCreateSpec(cloudfiletag.Table, sqlgraph.NewFieldSpec(cloudfiletag.FieldID, field.TypeUint64))
	)
	if id, ok := cftc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cftc.mutation.CreatedAt(); ok {
		_spec.SetField(cloudfiletag.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := cftc.mutation.UpdatedAt(); ok {
		_spec.SetField(cloudfiletag.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := cftc.mutation.Status(); ok {
		_spec.SetField(cloudfiletag.FieldStatus, field.TypeUint8, value)
		_node.Status = value
	}
	if value, ok := cftc.mutation.Name(); ok {
		_spec.SetField(cloudfiletag.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := cftc.mutation.Remark(); ok {
		_spec.SetField(cloudfiletag.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if nodes := cftc.mutation.CloudFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   cloudfiletag.CloudFilesTable,
			Columns: cloudfiletag.CloudFilesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cloudfile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CloudFileTagCreateBulk is the builder for creating many CloudFileTag entities in bulk.
type CloudFileTagCreateBulk struct {
	config
	builders []*CloudFileTagCreate
}

// Save creates the CloudFileTag entities in the database.
func (cftcb *CloudFileTagCreateBulk) Save(ctx context.Context) ([]*CloudFileTag, error) {
	specs := make([]*sqlgraph.CreateSpec, len(cftcb.builders))
	nodes := make([]*CloudFileTag, len(cftcb.builders))
	mutators := make([]Mutator, len(cftcb.builders))
	for i := range cftcb.builders {
		func(i int, root context.Context) {
			builder := cftcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CloudFileTagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cftcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cftcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cftcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cftcb *CloudFileTagCreateBulk) SaveX(ctx context.Context) []*CloudFileTag {
	v, err := cftcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cftcb *CloudFileTagCreateBulk) Exec(ctx context.Context) error {
	_, err := cftcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cftcb *CloudFileTagCreateBulk) ExecX(ctx context.Context) {
	if err := cftcb.Exec(ctx); err != nil {
		panic(err)
	}
}
