// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suyuan32/simple-admin-file/ent/cloudfile"
	"github.com/suyuan32/simple-admin-file/ent/cloudfiletag"
	"github.com/suyuan32/simple-admin-file/ent/predicate"
	"github.com/suyuan32/simple-admin-file/ent/storageprovider"
)

// CloudFileUpdate is the builder for updating CloudFile entities.
type CloudFileUpdate struct {
	config
	hooks    []Hook
	mutation *CloudFileMutation
}

// Where appends a list predicates to the CloudFileUpdate builder.
func (cfu *CloudFileUpdate) Where(ps ...predicate.CloudFile) *CloudFileUpdate {
	cfu.mutation.Where(ps...)
	return cfu
}

// SetUpdatedAt sets the "updated_at" field.
func (cfu *CloudFileUpdate) SetUpdatedAt(t time.Time) *CloudFileUpdate {
	cfu.mutation.SetUpdatedAt(t)
	return cfu
}

// SetState sets the "state" field.
func (cfu *CloudFileUpdate) SetState(b bool) *CloudFileUpdate {
	cfu.mutation.SetState(b)
	return cfu
}

// SetNillableState sets the "state" field if the given value is not nil.
func (cfu *CloudFileUpdate) SetNillableState(b *bool) *CloudFileUpdate {
	if b != nil {
		cfu.SetState(*b)
	}
	return cfu
}

// ClearState clears the value of the "state" field.
func (cfu *CloudFileUpdate) ClearState() *CloudFileUpdate {
	cfu.mutation.ClearState()
	return cfu
}

// SetName sets the "name" field.
func (cfu *CloudFileUpdate) SetName(s string) *CloudFileUpdate {
	cfu.mutation.SetName(s)
	return cfu
}

// SetURL sets the "url" field.
func (cfu *CloudFileUpdate) SetURL(s string) *CloudFileUpdate {
	cfu.mutation.SetURL(s)
	return cfu
}

// SetSize sets the "size" field.
func (cfu *CloudFileUpdate) SetSize(u uint64) *CloudFileUpdate {
	cfu.mutation.ResetSize()
	cfu.mutation.SetSize(u)
	return cfu
}

// AddSize adds u to the "size" field.
func (cfu *CloudFileUpdate) AddSize(u int64) *CloudFileUpdate {
	cfu.mutation.AddSize(u)
	return cfu
}

// SetFileType sets the "file_type" field.
func (cfu *CloudFileUpdate) SetFileType(u uint8) *CloudFileUpdate {
	cfu.mutation.ResetFileType()
	cfu.mutation.SetFileType(u)
	return cfu
}

// AddFileType adds u to the "file_type" field.
func (cfu *CloudFileUpdate) AddFileType(u int8) *CloudFileUpdate {
	cfu.mutation.AddFileType(u)
	return cfu
}

// SetUserID sets the "user_id" field.
func (cfu *CloudFileUpdate) SetUserID(s string) *CloudFileUpdate {
	cfu.mutation.SetUserID(s)
	return cfu
}

// SetStorageProvidersID sets the "storage_providers" edge to the StorageProvider entity by ID.
func (cfu *CloudFileUpdate) SetStorageProvidersID(id uint64) *CloudFileUpdate {
	cfu.mutation.SetStorageProvidersID(id)
	return cfu
}

// SetNillableStorageProvidersID sets the "storage_providers" edge to the StorageProvider entity by ID if the given value is not nil.
func (cfu *CloudFileUpdate) SetNillableStorageProvidersID(id *uint64) *CloudFileUpdate {
	if id != nil {
		cfu = cfu.SetStorageProvidersID(*id)
	}
	return cfu
}

// SetStorageProviders sets the "storage_providers" edge to the StorageProvider entity.
func (cfu *CloudFileUpdate) SetStorageProviders(s *StorageProvider) *CloudFileUpdate {
	return cfu.SetStorageProvidersID(s.ID)
}

// AddTagIDs adds the "tags" edge to the CloudFileTag entity by IDs.
func (cfu *CloudFileUpdate) AddTagIDs(ids ...uint64) *CloudFileUpdate {
	cfu.mutation.AddTagIDs(ids...)
	return cfu
}

// AddTags adds the "tags" edges to the CloudFileTag entity.
func (cfu *CloudFileUpdate) AddTags(c ...*CloudFileTag) *CloudFileUpdate {
	ids := make([]uint64, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cfu.AddTagIDs(ids...)
}

// Mutation returns the CloudFileMutation object of the builder.
func (cfu *CloudFileUpdate) Mutation() *CloudFileMutation {
	return cfu.mutation
}

// ClearStorageProviders clears the "storage_providers" edge to the StorageProvider entity.
func (cfu *CloudFileUpdate) ClearStorageProviders() *CloudFileUpdate {
	cfu.mutation.ClearStorageProviders()
	return cfu
}

// ClearTags clears all "tags" edges to the CloudFileTag entity.
func (cfu *CloudFileUpdate) ClearTags() *CloudFileUpdate {
	cfu.mutation.ClearTags()
	return cfu
}

// RemoveTagIDs removes the "tags" edge to CloudFileTag entities by IDs.
func (cfu *CloudFileUpdate) RemoveTagIDs(ids ...uint64) *CloudFileUpdate {
	cfu.mutation.RemoveTagIDs(ids...)
	return cfu
}

// RemoveTags removes "tags" edges to CloudFileTag entities.
func (cfu *CloudFileUpdate) RemoveTags(c ...*CloudFileTag) *CloudFileUpdate {
	ids := make([]uint64, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cfu.RemoveTagIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cfu *CloudFileUpdate) Save(ctx context.Context) (int, error) {
	cfu.defaults()
	return withHooks(ctx, cfu.sqlSave, cfu.mutation, cfu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cfu *CloudFileUpdate) SaveX(ctx context.Context) int {
	affected, err := cfu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cfu *CloudFileUpdate) Exec(ctx context.Context) error {
	_, err := cfu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cfu *CloudFileUpdate) ExecX(ctx context.Context) {
	if err := cfu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cfu *CloudFileUpdate) defaults() {
	if _, ok := cfu.mutation.UpdatedAt(); !ok {
		v := cloudfile.UpdateDefaultUpdatedAt()
		cfu.mutation.SetUpdatedAt(v)
	}
}

func (cfu *CloudFileUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(cloudfile.Table, cloudfile.Columns, sqlgraph.NewFieldSpec(cloudfile.FieldID, field.TypeUUID))
	if ps := cfu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cfu.mutation.UpdatedAt(); ok {
		_spec.SetField(cloudfile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cfu.mutation.State(); ok {
		_spec.SetField(cloudfile.FieldState, field.TypeBool, value)
	}
	if cfu.mutation.StateCleared() {
		_spec.ClearField(cloudfile.FieldState, field.TypeBool)
	}
	if value, ok := cfu.mutation.Name(); ok {
		_spec.SetField(cloudfile.FieldName, field.TypeString, value)
	}
	if value, ok := cfu.mutation.URL(); ok {
		_spec.SetField(cloudfile.FieldURL, field.TypeString, value)
	}
	if value, ok := cfu.mutation.Size(); ok {
		_spec.SetField(cloudfile.FieldSize, field.TypeUint64, value)
	}
	if value, ok := cfu.mutation.AddedSize(); ok {
		_spec.AddField(cloudfile.FieldSize, field.TypeUint64, value)
	}
	if value, ok := cfu.mutation.FileType(); ok {
		_spec.SetField(cloudfile.FieldFileType, field.TypeUint8, value)
	}
	if value, ok := cfu.mutation.AddedFileType(); ok {
		_spec.AddField(cloudfile.FieldFileType, field.TypeUint8, value)
	}
	if value, ok := cfu.mutation.UserID(); ok {
		_spec.SetField(cloudfile.FieldUserID, field.TypeString, value)
	}
	if cfu.mutation.StorageProvidersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cloudfile.StorageProvidersTable,
			Columns: []string{cloudfile.StorageProvidersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storageprovider.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cfu.mutation.StorageProvidersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cloudfile.StorageProvidersTable,
			Columns: []string{cloudfile.StorageProvidersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storageprovider.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cfu.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   cloudfile.TagsTable,
			Columns: cloudfile.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cloudfiletag.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cfu.mutation.RemovedTagsIDs(); len(nodes) > 0 && !cfu.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   cloudfile.TagsTable,
			Columns: cloudfile.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cloudfiletag.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cfu.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   cloudfile.TagsTable,
			Columns: cloudfile.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cloudfiletag.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cfu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cloudfile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cfu.mutation.done = true
	return n, nil
}

// CloudFileUpdateOne is the builder for updating a single CloudFile entity.
type CloudFileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CloudFileMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (cfuo *CloudFileUpdateOne) SetUpdatedAt(t time.Time) *CloudFileUpdateOne {
	cfuo.mutation.SetUpdatedAt(t)
	return cfuo
}

// SetState sets the "state" field.
func (cfuo *CloudFileUpdateOne) SetState(b bool) *CloudFileUpdateOne {
	cfuo.mutation.SetState(b)
	return cfuo
}

// SetNillableState sets the "state" field if the given value is not nil.
func (cfuo *CloudFileUpdateOne) SetNillableState(b *bool) *CloudFileUpdateOne {
	if b != nil {
		cfuo.SetState(*b)
	}
	return cfuo
}

// ClearState clears the value of the "state" field.
func (cfuo *CloudFileUpdateOne) ClearState() *CloudFileUpdateOne {
	cfuo.mutation.ClearState()
	return cfuo
}

// SetName sets the "name" field.
func (cfuo *CloudFileUpdateOne) SetName(s string) *CloudFileUpdateOne {
	cfuo.mutation.SetName(s)
	return cfuo
}

// SetURL sets the "url" field.
func (cfuo *CloudFileUpdateOne) SetURL(s string) *CloudFileUpdateOne {
	cfuo.mutation.SetURL(s)
	return cfuo
}

// SetSize sets the "size" field.
func (cfuo *CloudFileUpdateOne) SetSize(u uint64) *CloudFileUpdateOne {
	cfuo.mutation.ResetSize()
	cfuo.mutation.SetSize(u)
	return cfuo
}

// AddSize adds u to the "size" field.
func (cfuo *CloudFileUpdateOne) AddSize(u int64) *CloudFileUpdateOne {
	cfuo.mutation.AddSize(u)
	return cfuo
}

// SetFileType sets the "file_type" field.
func (cfuo *CloudFileUpdateOne) SetFileType(u uint8) *CloudFileUpdateOne {
	cfuo.mutation.ResetFileType()
	cfuo.mutation.SetFileType(u)
	return cfuo
}

// AddFileType adds u to the "file_type" field.
func (cfuo *CloudFileUpdateOne) AddFileType(u int8) *CloudFileUpdateOne {
	cfuo.mutation.AddFileType(u)
	return cfuo
}

// SetUserID sets the "user_id" field.
func (cfuo *CloudFileUpdateOne) SetUserID(s string) *CloudFileUpdateOne {
	cfuo.mutation.SetUserID(s)
	return cfuo
}

// SetStorageProvidersID sets the "storage_providers" edge to the StorageProvider entity by ID.
func (cfuo *CloudFileUpdateOne) SetStorageProvidersID(id uint64) *CloudFileUpdateOne {
	cfuo.mutation.SetStorageProvidersID(id)
	return cfuo
}

// SetNillableStorageProvidersID sets the "storage_providers" edge to the StorageProvider entity by ID if the given value is not nil.
func (cfuo *CloudFileUpdateOne) SetNillableStorageProvidersID(id *uint64) *CloudFileUpdateOne {
	if id != nil {
		cfuo = cfuo.SetStorageProvidersID(*id)
	}
	return cfuo
}

// SetStorageProviders sets the "storage_providers" edge to the StorageProvider entity.
func (cfuo *CloudFileUpdateOne) SetStorageProviders(s *StorageProvider) *CloudFileUpdateOne {
	return cfuo.SetStorageProvidersID(s.ID)
}

// AddTagIDs adds the "tags" edge to the CloudFileTag entity by IDs.
func (cfuo *CloudFileUpdateOne) AddTagIDs(ids ...uint64) *CloudFileUpdateOne {
	cfuo.mutation.AddTagIDs(ids...)
	return cfuo
}

// AddTags adds the "tags" edges to the CloudFileTag entity.
func (cfuo *CloudFileUpdateOne) AddTags(c ...*CloudFileTag) *CloudFileUpdateOne {
	ids := make([]uint64, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cfuo.AddTagIDs(ids...)
}

// Mutation returns the CloudFileMutation object of the builder.
func (cfuo *CloudFileUpdateOne) Mutation() *CloudFileMutation {
	return cfuo.mutation
}

// ClearStorageProviders clears the "storage_providers" edge to the StorageProvider entity.
func (cfuo *CloudFileUpdateOne) ClearStorageProviders() *CloudFileUpdateOne {
	cfuo.mutation.ClearStorageProviders()
	return cfuo
}

// ClearTags clears all "tags" edges to the CloudFileTag entity.
func (cfuo *CloudFileUpdateOne) ClearTags() *CloudFileUpdateOne {
	cfuo.mutation.ClearTags()
	return cfuo
}

// RemoveTagIDs removes the "tags" edge to CloudFileTag entities by IDs.
func (cfuo *CloudFileUpdateOne) RemoveTagIDs(ids ...uint64) *CloudFileUpdateOne {
	cfuo.mutation.RemoveTagIDs(ids...)
	return cfuo
}

// RemoveTags removes "tags" edges to CloudFileTag entities.
func (cfuo *CloudFileUpdateOne) RemoveTags(c ...*CloudFileTag) *CloudFileUpdateOne {
	ids := make([]uint64, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cfuo.RemoveTagIDs(ids...)
}

// Where appends a list predicates to the CloudFileUpdate builder.
func (cfuo *CloudFileUpdateOne) Where(ps ...predicate.CloudFile) *CloudFileUpdateOne {
	cfuo.mutation.Where(ps...)
	return cfuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cfuo *CloudFileUpdateOne) Select(field string, fields ...string) *CloudFileUpdateOne {
	cfuo.fields = append([]string{field}, fields...)
	return cfuo
}

// Save executes the query and returns the updated CloudFile entity.
func (cfuo *CloudFileUpdateOne) Save(ctx context.Context) (*CloudFile, error) {
	cfuo.defaults()
	return withHooks(ctx, cfuo.sqlSave, cfuo.mutation, cfuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cfuo *CloudFileUpdateOne) SaveX(ctx context.Context) *CloudFile {
	node, err := cfuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cfuo *CloudFileUpdateOne) Exec(ctx context.Context) error {
	_, err := cfuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cfuo *CloudFileUpdateOne) ExecX(ctx context.Context) {
	if err := cfuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cfuo *CloudFileUpdateOne) defaults() {
	if _, ok := cfuo.mutation.UpdatedAt(); !ok {
		v := cloudfile.UpdateDefaultUpdatedAt()
		cfuo.mutation.SetUpdatedAt(v)
	}
}

func (cfuo *CloudFileUpdateOne) sqlSave(ctx context.Context) (_node *CloudFile, err error) {
	_spec := sqlgraph.NewUpdateSpec(cloudfile.Table, cloudfile.Columns, sqlgraph.NewFieldSpec(cloudfile.FieldID, field.TypeUUID))
	id, ok := cfuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CloudFile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cfuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cloudfile.FieldID)
		for _, f := range fields {
			if !cloudfile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cloudfile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cfuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cfuo.mutation.UpdatedAt(); ok {
		_spec.SetField(cloudfile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cfuo.mutation.State(); ok {
		_spec.SetField(cloudfile.FieldState, field.TypeBool, value)
	}
	if cfuo.mutation.StateCleared() {
		_spec.ClearField(cloudfile.FieldState, field.TypeBool)
	}
	if value, ok := cfuo.mutation.Name(); ok {
		_spec.SetField(cloudfile.FieldName, field.TypeString, value)
	}
	if value, ok := cfuo.mutation.URL(); ok {
		_spec.SetField(cloudfile.FieldURL, field.TypeString, value)
	}
	if value, ok := cfuo.mutation.Size(); ok {
		_spec.SetField(cloudfile.FieldSize, field.TypeUint64, value)
	}
	if value, ok := cfuo.mutation.AddedSize(); ok {
		_spec.AddField(cloudfile.FieldSize, field.TypeUint64, value)
	}
	if value, ok := cfuo.mutation.FileType(); ok {
		_spec.SetField(cloudfile.FieldFileType, field.TypeUint8, value)
	}
	if value, ok := cfuo.mutation.AddedFileType(); ok {
		_spec.AddField(cloudfile.FieldFileType, field.TypeUint8, value)
	}
	if value, ok := cfuo.mutation.UserID(); ok {
		_spec.SetField(cloudfile.FieldUserID, field.TypeString, value)
	}
	if cfuo.mutation.StorageProvidersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cloudfile.StorageProvidersTable,
			Columns: []string{cloudfile.StorageProvidersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storageprovider.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cfuo.mutation.StorageProvidersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cloudfile.StorageProvidersTable,
			Columns: []string{cloudfile.StorageProvidersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storageprovider.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cfuo.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   cloudfile.TagsTable,
			Columns: cloudfile.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cloudfiletag.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cfuo.mutation.RemovedTagsIDs(); len(nodes) > 0 && !cfuo.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   cloudfile.TagsTable,
			Columns: cloudfile.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cloudfiletag.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cfuo.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   cloudfile.TagsTable,
			Columns: cloudfile.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cloudfiletag.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CloudFile{config: cfuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cfuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cloudfile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cfuo.mutation.done = true
	return _node, nil
}
