// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suyuan32/simple-admin-file/ent/cloudfile"
	"github.com/suyuan32/simple-admin-file/ent/predicate"
	"github.com/suyuan32/simple-admin-file/ent/storageprovider"
)

// StorageProviderQuery is the builder for querying StorageProvider entities.
type StorageProviderQuery struct {
	config
	ctx            *QueryContext
	order          []storageprovider.OrderOption
	inters         []Interceptor
	predicates     []predicate.StorageProvider
	withCloudfiles *CloudFileQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StorageProviderQuery builder.
func (_q *StorageProviderQuery) Where(ps ...predicate.StorageProvider) *StorageProviderQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *StorageProviderQuery) Limit(limit int) *StorageProviderQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *StorageProviderQuery) Offset(offset int) *StorageProviderQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *StorageProviderQuery) Unique(unique bool) *StorageProviderQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *StorageProviderQuery) Order(o ...storageprovider.OrderOption) *StorageProviderQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCloudfiles chains the current query on the "cloudfiles" edge.
func (_q *StorageProviderQuery) QueryCloudfiles() *CloudFileQuery {
	query := (&CloudFileClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(storageprovider.Table, storageprovider.FieldID, selector),
			sqlgraph.To(cloudfile.Table, cloudfile.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, storageprovider.CloudfilesTable, storageprovider.CloudfilesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first StorageProvider entity from the query.
// Returns a *NotFoundError when no StorageProvider was found.
func (_q *StorageProviderQuery) First(ctx context.Context) (*StorageProvider, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{storageprovider.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *StorageProviderQuery) FirstX(ctx context.Context) *StorageProvider {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StorageProvider ID from the query.
// Returns a *NotFoundError when no StorageProvider ID was found.
func (_q *StorageProviderQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{storageprovider.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *StorageProviderQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StorageProvider entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StorageProvider entity is found.
// Returns a *NotFoundError when no StorageProvider entities are found.
func (_q *StorageProviderQuery) Only(ctx context.Context) (*StorageProvider, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{storageprovider.Label}
	default:
		return nil, &NotSingularError{storageprovider.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *StorageProviderQuery) OnlyX(ctx context.Context) *StorageProvider {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StorageProvider ID in the query.
// Returns a *NotSingularError when more than one StorageProvider ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *StorageProviderQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{storageprovider.Label}
	default:
		err = &NotSingularError{storageprovider.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *StorageProviderQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StorageProviders.
func (_q *StorageProviderQuery) All(ctx context.Context) ([]*StorageProvider, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StorageProvider, *StorageProviderQuery]()
	return withInterceptors[[]*StorageProvider](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *StorageProviderQuery) AllX(ctx context.Context) []*StorageProvider {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StorageProvider IDs.
func (_q *StorageProviderQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(storageprovider.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *StorageProviderQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *StorageProviderQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*StorageProviderQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *StorageProviderQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *StorageProviderQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *StorageProviderQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StorageProviderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *StorageProviderQuery) Clone() *StorageProviderQuery {
	if _q == nil {
		return nil
	}
	return &StorageProviderQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]storageprovider.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.StorageProvider{}, _q.predicates...),
		withCloudfiles: _q.withCloudfiles.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCloudfiles tells the query-builder to eager-load the nodes that are connected to
// the "cloudfiles" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StorageProviderQuery) WithCloudfiles(opts ...func(*CloudFileQuery)) *StorageProviderQuery {
	query := (&CloudFileClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCloudfiles = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StorageProvider.Query().
//		GroupBy(storageprovider.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *StorageProviderQuery) GroupBy(field string, fields ...string) *StorageProviderGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StorageProviderGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = storageprovider.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.StorageProvider.Query().
//		Select(storageprovider.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *StorageProviderQuery) Select(fields ...string) *StorageProviderSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &StorageProviderSelect{StorageProviderQuery: _q}
	sbuild.label = storageprovider.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StorageProviderSelect configured with the given aggregations.
func (_q *StorageProviderQuery) Aggregate(fns ...AggregateFunc) *StorageProviderSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *StorageProviderQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !storageprovider.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *StorageProviderQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StorageProvider, error) {
	var (
		nodes       = []*StorageProvider{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withCloudfiles != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StorageProvider).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StorageProvider{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCloudfiles; query != nil {
		if err := _q.loadCloudfiles(ctx, query, nodes,
			func(n *StorageProvider) { n.Edges.Cloudfiles = []*CloudFile{} },
			func(n *StorageProvider, e *CloudFile) { n.Edges.Cloudfiles = append(n.Edges.Cloudfiles, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *StorageProviderQuery) loadCloudfiles(ctx context.Context, query *CloudFileQuery, nodes []*StorageProvider, init func(*StorageProvider), assign func(*StorageProvider, *CloudFile)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*StorageProvider)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.CloudFile(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(storageprovider.CloudfilesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.cloud_file_storage_providers
		if fk == nil {
			return fmt.Errorf(`foreign-key "cloud_file_storage_providers" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "cloud_file_storage_providers" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *StorageProviderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *StorageProviderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(storageprovider.Table, storageprovider.Columns, sqlgraph.NewFieldSpec(storageprovider.FieldID, field.TypeUint64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, storageprovider.FieldID)
		for i := range fields {
			if fields[i] != storageprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *StorageProviderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(storageprovider.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = storageprovider.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StorageProviderGroupBy is the group-by builder for StorageProvider entities.
type StorageProviderGroupBy struct {
	selector
	build *StorageProviderQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *StorageProviderGroupBy) Aggregate(fns ...AggregateFunc) *StorageProviderGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *StorageProviderGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StorageProviderQuery, *StorageProviderGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *StorageProviderGroupBy) sqlScan(ctx context.Context, root *StorageProviderQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StorageProviderSelect is the builder for selecting fields of StorageProvider entities.
type StorageProviderSelect struct {
	*StorageProviderQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *StorageProviderSelect) Aggregate(fns ...AggregateFunc) *StorageProviderSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *StorageProviderSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StorageProviderQuery, *StorageProviderSelect](ctx, _s.StorageProviderQuery, _s, _s.inters, v)
}

func (_s *StorageProviderSelect) sqlScan(ctx context.Context, root *StorageProviderQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
